debug

diff --git a/packages/foundry/Makefile b/packages/foundry/Makefile
--- a/packages/foundry/Makefile
+++ b/packages/foundry/Makefile
@@ -1,7 +1,73 @@
-verify-sepolia:
-	@echo "Verifying contracts on Sepolia network"
-	forge script script/VerifyAll.s.sol --ffi --chain-id 11155111
+.PHONY: build deploy generate-abis get-address account chain compile flatten fork format lint test verify
 
-verify-all:
-	@echo "Verifying all contracts"
-	forge script script/VerifyAll.s.sol --ffi
+DEPLOY_SCRIPT ?= script/Deploy.s.sol
+SENDER ?= 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720
+
+# setup wallet for anvil
+setup-anvil-wallet:
+	shx rm ~/.foundry/keystores/scaffold-eth-default 2>/dev/null; \
+	shx rm -rf broadcast/Deploy.s.sol/31337
+	cast wallet import --private-key 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356 --unsafe-password 'localhost' scaffold-eth-default
+
+# Start local chain
+chain: setup-anvil-wallet
+	anvil
+
+# Start a fork
+fork: setup-anvil-wallet
+	anvil --fork-url ${FORK_URL} --chain-id 31337
+
+# Deploy the contracts
+deploy:
+	@if [ ! -f "$(DEPLOY_SCRIPT)" ]; then \
+		echo "Error: Deploy script '$(DEPLOY_SCRIPT)' not found"; \
+		exit 1; \
+	fi
+	@if [ "$(RPC_URL)" = "localhost" ]; then \
+		if [ "$(ETH_KEYSTORE_ACCOUNT)" = "scaffold-eth-default" ]; then \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --password localhost --broadcast --legacy --ffi --sender $(SENDER); \
+		else \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --broadcast --legacy --ffi --sender $(SENDER); \
+		fi \
+	else \
+		forge script $(DEPLOY_SCRIPT) --rpc-url $(RPC_URL) --broadcast --legacy --ffi --sender $(SENDER); \
+	fi
+
+# Deploy and generate ABIs
+deploy-and-generate-abis: deploy generate-abis
+
+# Generate TypeScript ABIs
+generate-abis:
+	node scripts-js/generateTsAbis.js
+
+# List account
+account:
+	@node scripts-js/checkAccountBalance.js
+
+# Get address of a keystore
+get-address:
+	@cast wallet address --account $(ACCOUNT_NAME)
+
+# Compile contracts
+compile:
+	forge compile
+
+# Flatten contracts
+flatten:
+	forge flatten
+
+# Format code
+format:
+	forge fmt && prettier --write ./scripts-js/**/*.js
+
+# Lint code
+lint:
+	forge fmt --check && prettier --check ./script/**/*.js
+
+# Run tests
+test:
+	forge test
+
+# Verify contracts
+verify:
+	forge script script/VerifyAll.s.sol --ffi --rpc-url $(RPC_URL)
